mergeHTML <- function(name,loc=".")
  {
    t1.file <- paste(loc,"/","template1.html",sep="")
    t2.file <- paste(loc,"/","template2.html",sep="")
    in.file <- paste(loc,"/",name,".html",sep="")
    out.file <- paste(loc,"/compiled/",name,".html",sep="")
    f <- file(out.file,"w")
    buffer <- readLines(t1.file)
    writeLines(buffer,con=f)
    buffer <- readLines(in.file)
    writeLines(buffer,con=f)
    buffer <- readLines(t2.file)
    writeLines(buffer,con=f)
    close(f)
  }
